theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
encding: utf-8
plugins:
  - jekyll-github-metadata
github : [metadata]
repository: starkoka/Jekyll-test